package cargoes.model.po;

import java.util.Date;

public class Authority {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authority.id
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authority.code
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authority.name
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authority.description
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authority.create_date
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authority.modify_time
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authority.id
     *
     * @return the value of sys_authority.id
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authority.id
     *
     * @param id the value for sys_authority.id
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authority.code
     *
     * @return the value of sys_authority.code
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authority.code
     *
     * @param code the value for sys_authority.code
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authority.name
     *
     * @return the value of sys_authority.name
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authority.name
     *
     * @param name the value for sys_authority.name
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authority.description
     *
     * @return the value of sys_authority.description
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authority.description
     *
     * @param description the value for sys_authority.description
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authority.create_date
     *
     * @return the value of sys_authority.create_date
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authority.create_date
     *
     * @param createDate the value for sys_authority.create_date
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authority.modify_time
     *
     * @return the value of sys_authority.modify_time
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authority.modify_time
     *
     * @param modifyTime the value for sys_authority.modify_time
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}