package cargoes.model.po;

import java.util.Date;

public class Department {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department.id
     *
     * @mbggenerated Wed Jun 06 11:27:35 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department.code
     *
     * @mbggenerated Wed Jun 06 11:27:35 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department.name
     *
     * @mbggenerated Wed Jun 06 11:27:35 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department.description
     *
     * @mbggenerated Wed Jun 06 11:27:35 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department.parent_id
     *
     * @mbggenerated Wed Jun 06 11:27:35 CST 2018
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department.order
     *
     * @mbggenerated Wed Jun 06 11:27:35 CST 2018
     */
    private Integer order;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department.create_time
     *
     * @mbggenerated Wed Jun 06 11:27:35 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department.modify_time
     *
     * @mbggenerated Wed Jun 06 11:27:35 CST 2018
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.id
     *
     * @return the value of sys_department.id
     *
     * @mbggenerated Wed Jun 06 11:27:35 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.id
     *
     * @param id the value for sys_department.id
     *
     * @mbggenerated Wed Jun 06 11:27:35 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.code
     *
     * @return the value of sys_department.code
     *
     * @mbggenerated Wed Jun 06 11:27:35 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.code
     *
     * @param code the value for sys_department.code
     *
     * @mbggenerated Wed Jun 06 11:27:35 CST 2018
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.name
     *
     * @return the value of sys_department.name
     *
     * @mbggenerated Wed Jun 06 11:27:35 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.name
     *
     * @param name the value for sys_department.name
     *
     * @mbggenerated Wed Jun 06 11:27:35 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.description
     *
     * @return the value of sys_department.description
     *
     * @mbggenerated Wed Jun 06 11:27:35 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.description
     *
     * @param description the value for sys_department.description
     *
     * @mbggenerated Wed Jun 06 11:27:35 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.parent_id
     *
     * @return the value of sys_department.parent_id
     *
     * @mbggenerated Wed Jun 06 11:27:35 CST 2018
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.parent_id
     *
     * @param parentId the value for sys_department.parent_id
     *
     * @mbggenerated Wed Jun 06 11:27:35 CST 2018
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.order
     *
     * @return the value of sys_department.order
     *
     * @mbggenerated Wed Jun 06 11:27:35 CST 2018
     */
    public Integer getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.order
     *
     * @param order the value for sys_department.order
     *
     * @mbggenerated Wed Jun 06 11:27:35 CST 2018
     */
    public void setOrder(Integer order) {
        this.order = order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.create_time
     *
     * @return the value of sys_department.create_time
     *
     * @mbggenerated Wed Jun 06 11:27:35 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.create_time
     *
     * @param createTime the value for sys_department.create_time
     *
     * @mbggenerated Wed Jun 06 11:27:35 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.modify_time
     *
     * @return the value of sys_department.modify_time
     *
     * @mbggenerated Wed Jun 06 11:27:35 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.modify_time
     *
     * @param modifyTime the value for sys_department.modify_time
     *
     * @mbggenerated Wed Jun 06 11:27:35 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}