package cargoes.model.po;

import java.util.Date;

public class OperationLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.id
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.user_id
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.request_url
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    private String requestUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.request_args
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    private String requestArgs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.option_desc
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    private String optionDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.ip
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.option_time
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    private Date optionTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.option_resutlt
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    private Integer optionResutlt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.error_message
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    private String errorMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.error_from
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    private String errorFrom;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.id
     *
     * @return the value of sys_operation_log.id
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.id
     *
     * @param id the value for sys_operation_log.id
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.user_id
     *
     * @return the value of sys_operation_log.user_id
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.user_id
     *
     * @param userId the value for sys_operation_log.user_id
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.request_url
     *
     * @return the value of sys_operation_log.request_url
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    public String getRequestUrl() {
        return requestUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.request_url
     *
     * @param requestUrl the value for sys_operation_log.request_url
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    public void setRequestUrl(String requestUrl) {
        this.requestUrl = requestUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.request_args
     *
     * @return the value of sys_operation_log.request_args
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    public String getRequestArgs() {
        return requestArgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.request_args
     *
     * @param requestArgs the value for sys_operation_log.request_args
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    public void setRequestArgs(String requestArgs) {
        this.requestArgs = requestArgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.option_desc
     *
     * @return the value of sys_operation_log.option_desc
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    public String getOptionDesc() {
        return optionDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.option_desc
     *
     * @param optionDesc the value for sys_operation_log.option_desc
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    public void setOptionDesc(String optionDesc) {
        this.optionDesc = optionDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.ip
     *
     * @return the value of sys_operation_log.ip
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.ip
     *
     * @param ip the value for sys_operation_log.ip
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.option_time
     *
     * @return the value of sys_operation_log.option_time
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    public Date getOptionTime() {
        return optionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.option_time
     *
     * @param optionTime the value for sys_operation_log.option_time
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    public void setOptionTime(Date optionTime) {
        this.optionTime = optionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.option_resutlt
     *
     * @return the value of sys_operation_log.option_resutlt
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    public Integer getOptionResutlt() {
        return optionResutlt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.option_resutlt
     *
     * @param optionResutlt the value for sys_operation_log.option_resutlt
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    public void setOptionResutlt(Integer optionResutlt) {
        this.optionResutlt = optionResutlt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.error_message
     *
     * @return the value of sys_operation_log.error_message
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    public String getErrorMessage() {
        return errorMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.error_message
     *
     * @param errorMessage the value for sys_operation_log.error_message
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.error_from
     *
     * @return the value of sys_operation_log.error_from
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    public String getErrorFrom() {
        return errorFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.error_from
     *
     * @param errorFrom the value for sys_operation_log.error_from
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    public void setErrorFrom(String errorFrom) {
        this.errorFrom = errorFrom;
    }
}