package cargoes.model.po;

import java.util.Date;

public class OperationLog {
	
	public static int OPERATION_STATUS_SUCCESS = 1;
	public static int  OPERATION_STATUS_FAIL = 0;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.id
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.user_id
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.ip
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.request_url
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    private String requestUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.request_type
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    private String requestType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.request_info
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    private String requestInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.operation_desc
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    private String operationDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.operation_time
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    private Date operationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.operation_status
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    private Integer operationStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.consumed_time
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    private Integer consumedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.invoked_method
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    private String invokedMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.error_message
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    private String errorMessage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.id
     *
     * @return the value of sys_operation_log.id
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.id
     *
     * @param id the value for sys_operation_log.id
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.user_id
     *
     * @return the value of sys_operation_log.user_id
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.user_id
     *
     * @param userId the value for sys_operation_log.user_id
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.ip
     *
     * @return the value of sys_operation_log.ip
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.ip
     *
     * @param ip the value for sys_operation_log.ip
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.request_url
     *
     * @return the value of sys_operation_log.request_url
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    public String getRequestUrl() {
        return requestUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.request_url
     *
     * @param requestUrl the value for sys_operation_log.request_url
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    public void setRequestUrl(String requestUrl) {
        this.requestUrl = requestUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.request_type
     *
     * @return the value of sys_operation_log.request_type
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    public String getRequestType() {
        return requestType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.request_type
     *
     * @param requestType the value for sys_operation_log.request_type
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    public void setRequestType(String requestType) {
        this.requestType = requestType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.request_info
     *
     * @return the value of sys_operation_log.request_info
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    public String getRequestInfo() {
        return requestInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.request_info
     *
     * @param requestInfo the value for sys_operation_log.request_info
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    public void setRequestInfo(String requestInfo) {
        this.requestInfo = requestInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.operation_desc
     *
     * @return the value of sys_operation_log.operation_desc
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    public String getOperationDesc() {
        return operationDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.operation_desc
     *
     * @param operationDesc the value for sys_operation_log.operation_desc
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    public void setOperationDesc(String operationDesc) {
        this.operationDesc = operationDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.operation_time
     *
     * @return the value of sys_operation_log.operation_time
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    public Date getOperationTime() {
        return operationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.operation_time
     *
     * @param operationTime the value for sys_operation_log.operation_time
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    public void setOperationTime(Date operationTime) {
        this.operationTime = operationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.operation_status
     *
     * @return the value of sys_operation_log.operation_status
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    public Integer getOperationStatus() {
        return operationStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.operation_status
     *
     * @param operationStatus the value for sys_operation_log.operation_status
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    public void setOperationStatus(Integer operationStatus) {
        this.operationStatus = operationStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.consumed_time
     *
     * @return the value of sys_operation_log.consumed_time
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    public Integer getConsumedTime() {
        return consumedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.consumed_time
     *
     * @param consumedTime the value for sys_operation_log.consumed_time
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    public void setConsumedTime(Integer consumedTime) {
        this.consumedTime = consumedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.invoked_method
     *
     * @return the value of sys_operation_log.invoked_method
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    public String getInvokedMethod() {
        return invokedMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.invoked_method
     *
     * @param invokedMethod the value for sys_operation_log.invoked_method
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    public void setInvokedMethod(String invokedMethod) {
        this.invokedMethod = invokedMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.error_message
     *
     * @return the value of sys_operation_log.error_message
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    public String getErrorMessage() {
        return errorMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.error_message
     *
     * @param errorMessage the value for sys_operation_log.error_message
     *
     * @mbggenerated Wed May 30 10:17:25 CST 2018
     */
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }
}