package cargoes.model.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OperationLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_operation_log
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_operation_log
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_operation_log
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_operation_log
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    public OperationLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_operation_log
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_operation_log
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_operation_log
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_operation_log
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_operation_log
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_operation_log
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_operation_log
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_operation_log
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_operation_log
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_operation_log
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_operation_log
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andRequestUrlIsNull() {
            addCriterion("request_url is null");
            return (Criteria) this;
        }

        public Criteria andRequestUrlIsNotNull() {
            addCriterion("request_url is not null");
            return (Criteria) this;
        }

        public Criteria andRequestUrlEqualTo(String value) {
            addCriterion("request_url =", value, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlNotEqualTo(String value) {
            addCriterion("request_url <>", value, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlGreaterThan(String value) {
            addCriterion("request_url >", value, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlGreaterThanOrEqualTo(String value) {
            addCriterion("request_url >=", value, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlLessThan(String value) {
            addCriterion("request_url <", value, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlLessThanOrEqualTo(String value) {
            addCriterion("request_url <=", value, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlLike(String value) {
            addCriterion("request_url like", value, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlNotLike(String value) {
            addCriterion("request_url not like", value, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlIn(List<String> values) {
            addCriterion("request_url in", values, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlNotIn(List<String> values) {
            addCriterion("request_url not in", values, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlBetween(String value1, String value2) {
            addCriterion("request_url between", value1, value2, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlNotBetween(String value1, String value2) {
            addCriterion("request_url not between", value1, value2, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestArgsIsNull() {
            addCriterion("request_args is null");
            return (Criteria) this;
        }

        public Criteria andRequestArgsIsNotNull() {
            addCriterion("request_args is not null");
            return (Criteria) this;
        }

        public Criteria andRequestArgsEqualTo(String value) {
            addCriterion("request_args =", value, "requestArgs");
            return (Criteria) this;
        }

        public Criteria andRequestArgsNotEqualTo(String value) {
            addCriterion("request_args <>", value, "requestArgs");
            return (Criteria) this;
        }

        public Criteria andRequestArgsGreaterThan(String value) {
            addCriterion("request_args >", value, "requestArgs");
            return (Criteria) this;
        }

        public Criteria andRequestArgsGreaterThanOrEqualTo(String value) {
            addCriterion("request_args >=", value, "requestArgs");
            return (Criteria) this;
        }

        public Criteria andRequestArgsLessThan(String value) {
            addCriterion("request_args <", value, "requestArgs");
            return (Criteria) this;
        }

        public Criteria andRequestArgsLessThanOrEqualTo(String value) {
            addCriterion("request_args <=", value, "requestArgs");
            return (Criteria) this;
        }

        public Criteria andRequestArgsLike(String value) {
            addCriterion("request_args like", value, "requestArgs");
            return (Criteria) this;
        }

        public Criteria andRequestArgsNotLike(String value) {
            addCriterion("request_args not like", value, "requestArgs");
            return (Criteria) this;
        }

        public Criteria andRequestArgsIn(List<String> values) {
            addCriterion("request_args in", values, "requestArgs");
            return (Criteria) this;
        }

        public Criteria andRequestArgsNotIn(List<String> values) {
            addCriterion("request_args not in", values, "requestArgs");
            return (Criteria) this;
        }

        public Criteria andRequestArgsBetween(String value1, String value2) {
            addCriterion("request_args between", value1, value2, "requestArgs");
            return (Criteria) this;
        }

        public Criteria andRequestArgsNotBetween(String value1, String value2) {
            addCriterion("request_args not between", value1, value2, "requestArgs");
            return (Criteria) this;
        }

        public Criteria andOptionDescIsNull() {
            addCriterion("option_desc is null");
            return (Criteria) this;
        }

        public Criteria andOptionDescIsNotNull() {
            addCriterion("option_desc is not null");
            return (Criteria) this;
        }

        public Criteria andOptionDescEqualTo(String value) {
            addCriterion("option_desc =", value, "optionDesc");
            return (Criteria) this;
        }

        public Criteria andOptionDescNotEqualTo(String value) {
            addCriterion("option_desc <>", value, "optionDesc");
            return (Criteria) this;
        }

        public Criteria andOptionDescGreaterThan(String value) {
            addCriterion("option_desc >", value, "optionDesc");
            return (Criteria) this;
        }

        public Criteria andOptionDescGreaterThanOrEqualTo(String value) {
            addCriterion("option_desc >=", value, "optionDesc");
            return (Criteria) this;
        }

        public Criteria andOptionDescLessThan(String value) {
            addCriterion("option_desc <", value, "optionDesc");
            return (Criteria) this;
        }

        public Criteria andOptionDescLessThanOrEqualTo(String value) {
            addCriterion("option_desc <=", value, "optionDesc");
            return (Criteria) this;
        }

        public Criteria andOptionDescLike(String value) {
            addCriterion("option_desc like", value, "optionDesc");
            return (Criteria) this;
        }

        public Criteria andOptionDescNotLike(String value) {
            addCriterion("option_desc not like", value, "optionDesc");
            return (Criteria) this;
        }

        public Criteria andOptionDescIn(List<String> values) {
            addCriterion("option_desc in", values, "optionDesc");
            return (Criteria) this;
        }

        public Criteria andOptionDescNotIn(List<String> values) {
            addCriterion("option_desc not in", values, "optionDesc");
            return (Criteria) this;
        }

        public Criteria andOptionDescBetween(String value1, String value2) {
            addCriterion("option_desc between", value1, value2, "optionDesc");
            return (Criteria) this;
        }

        public Criteria andOptionDescNotBetween(String value1, String value2) {
            addCriterion("option_desc not between", value1, value2, "optionDesc");
            return (Criteria) this;
        }

        public Criteria andIpIsNull() {
            addCriterion("ip is null");
            return (Criteria) this;
        }

        public Criteria andIpIsNotNull() {
            addCriterion("ip is not null");
            return (Criteria) this;
        }

        public Criteria andIpEqualTo(String value) {
            addCriterion("ip =", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotEqualTo(String value) {
            addCriterion("ip <>", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThan(String value) {
            addCriterion("ip >", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThanOrEqualTo(String value) {
            addCriterion("ip >=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThan(String value) {
            addCriterion("ip <", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThanOrEqualTo(String value) {
            addCriterion("ip <=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLike(String value) {
            addCriterion("ip like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotLike(String value) {
            addCriterion("ip not like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpIn(List<String> values) {
            addCriterion("ip in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotIn(List<String> values) {
            addCriterion("ip not in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpBetween(String value1, String value2) {
            addCriterion("ip between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotBetween(String value1, String value2) {
            addCriterion("ip not between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andOptionTimeIsNull() {
            addCriterion("option_time is null");
            return (Criteria) this;
        }

        public Criteria andOptionTimeIsNotNull() {
            addCriterion("option_time is not null");
            return (Criteria) this;
        }

        public Criteria andOptionTimeEqualTo(Date value) {
            addCriterion("option_time =", value, "optionTime");
            return (Criteria) this;
        }

        public Criteria andOptionTimeNotEqualTo(Date value) {
            addCriterion("option_time <>", value, "optionTime");
            return (Criteria) this;
        }

        public Criteria andOptionTimeGreaterThan(Date value) {
            addCriterion("option_time >", value, "optionTime");
            return (Criteria) this;
        }

        public Criteria andOptionTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("option_time >=", value, "optionTime");
            return (Criteria) this;
        }

        public Criteria andOptionTimeLessThan(Date value) {
            addCriterion("option_time <", value, "optionTime");
            return (Criteria) this;
        }

        public Criteria andOptionTimeLessThanOrEqualTo(Date value) {
            addCriterion("option_time <=", value, "optionTime");
            return (Criteria) this;
        }

        public Criteria andOptionTimeIn(List<Date> values) {
            addCriterion("option_time in", values, "optionTime");
            return (Criteria) this;
        }

        public Criteria andOptionTimeNotIn(List<Date> values) {
            addCriterion("option_time not in", values, "optionTime");
            return (Criteria) this;
        }

        public Criteria andOptionTimeBetween(Date value1, Date value2) {
            addCriterion("option_time between", value1, value2, "optionTime");
            return (Criteria) this;
        }

        public Criteria andOptionTimeNotBetween(Date value1, Date value2) {
            addCriterion("option_time not between", value1, value2, "optionTime");
            return (Criteria) this;
        }

        public Criteria andOptionResutltIsNull() {
            addCriterion("option_resutlt is null");
            return (Criteria) this;
        }

        public Criteria andOptionResutltIsNotNull() {
            addCriterion("option_resutlt is not null");
            return (Criteria) this;
        }

        public Criteria andOptionResutltEqualTo(Integer value) {
            addCriterion("option_resutlt =", value, "optionResutlt");
            return (Criteria) this;
        }

        public Criteria andOptionResutltNotEqualTo(Integer value) {
            addCriterion("option_resutlt <>", value, "optionResutlt");
            return (Criteria) this;
        }

        public Criteria andOptionResutltGreaterThan(Integer value) {
            addCriterion("option_resutlt >", value, "optionResutlt");
            return (Criteria) this;
        }

        public Criteria andOptionResutltGreaterThanOrEqualTo(Integer value) {
            addCriterion("option_resutlt >=", value, "optionResutlt");
            return (Criteria) this;
        }

        public Criteria andOptionResutltLessThan(Integer value) {
            addCriterion("option_resutlt <", value, "optionResutlt");
            return (Criteria) this;
        }

        public Criteria andOptionResutltLessThanOrEqualTo(Integer value) {
            addCriterion("option_resutlt <=", value, "optionResutlt");
            return (Criteria) this;
        }

        public Criteria andOptionResutltIn(List<Integer> values) {
            addCriterion("option_resutlt in", values, "optionResutlt");
            return (Criteria) this;
        }

        public Criteria andOptionResutltNotIn(List<Integer> values) {
            addCriterion("option_resutlt not in", values, "optionResutlt");
            return (Criteria) this;
        }

        public Criteria andOptionResutltBetween(Integer value1, Integer value2) {
            addCriterion("option_resutlt between", value1, value2, "optionResutlt");
            return (Criteria) this;
        }

        public Criteria andOptionResutltNotBetween(Integer value1, Integer value2) {
            addCriterion("option_resutlt not between", value1, value2, "optionResutlt");
            return (Criteria) this;
        }

        public Criteria andErrorMessageIsNull() {
            addCriterion("error_message is null");
            return (Criteria) this;
        }

        public Criteria andErrorMessageIsNotNull() {
            addCriterion("error_message is not null");
            return (Criteria) this;
        }

        public Criteria andErrorMessageEqualTo(String value) {
            addCriterion("error_message =", value, "errorMessage");
            return (Criteria) this;
        }

        public Criteria andErrorMessageNotEqualTo(String value) {
            addCriterion("error_message <>", value, "errorMessage");
            return (Criteria) this;
        }

        public Criteria andErrorMessageGreaterThan(String value) {
            addCriterion("error_message >", value, "errorMessage");
            return (Criteria) this;
        }

        public Criteria andErrorMessageGreaterThanOrEqualTo(String value) {
            addCriterion("error_message >=", value, "errorMessage");
            return (Criteria) this;
        }

        public Criteria andErrorMessageLessThan(String value) {
            addCriterion("error_message <", value, "errorMessage");
            return (Criteria) this;
        }

        public Criteria andErrorMessageLessThanOrEqualTo(String value) {
            addCriterion("error_message <=", value, "errorMessage");
            return (Criteria) this;
        }

        public Criteria andErrorMessageLike(String value) {
            addCriterion("error_message like", value, "errorMessage");
            return (Criteria) this;
        }

        public Criteria andErrorMessageNotLike(String value) {
            addCriterion("error_message not like", value, "errorMessage");
            return (Criteria) this;
        }

        public Criteria andErrorMessageIn(List<String> values) {
            addCriterion("error_message in", values, "errorMessage");
            return (Criteria) this;
        }

        public Criteria andErrorMessageNotIn(List<String> values) {
            addCriterion("error_message not in", values, "errorMessage");
            return (Criteria) this;
        }

        public Criteria andErrorMessageBetween(String value1, String value2) {
            addCriterion("error_message between", value1, value2, "errorMessage");
            return (Criteria) this;
        }

        public Criteria andErrorMessageNotBetween(String value1, String value2) {
            addCriterion("error_message not between", value1, value2, "errorMessage");
            return (Criteria) this;
        }

        public Criteria andErrorFromIsNull() {
            addCriterion("error_from is null");
            return (Criteria) this;
        }

        public Criteria andErrorFromIsNotNull() {
            addCriterion("error_from is not null");
            return (Criteria) this;
        }

        public Criteria andErrorFromEqualTo(String value) {
            addCriterion("error_from =", value, "errorFrom");
            return (Criteria) this;
        }

        public Criteria andErrorFromNotEqualTo(String value) {
            addCriterion("error_from <>", value, "errorFrom");
            return (Criteria) this;
        }

        public Criteria andErrorFromGreaterThan(String value) {
            addCriterion("error_from >", value, "errorFrom");
            return (Criteria) this;
        }

        public Criteria andErrorFromGreaterThanOrEqualTo(String value) {
            addCriterion("error_from >=", value, "errorFrom");
            return (Criteria) this;
        }

        public Criteria andErrorFromLessThan(String value) {
            addCriterion("error_from <", value, "errorFrom");
            return (Criteria) this;
        }

        public Criteria andErrorFromLessThanOrEqualTo(String value) {
            addCriterion("error_from <=", value, "errorFrom");
            return (Criteria) this;
        }

        public Criteria andErrorFromLike(String value) {
            addCriterion("error_from like", value, "errorFrom");
            return (Criteria) this;
        }

        public Criteria andErrorFromNotLike(String value) {
            addCriterion("error_from not like", value, "errorFrom");
            return (Criteria) this;
        }

        public Criteria andErrorFromIn(List<String> values) {
            addCriterion("error_from in", values, "errorFrom");
            return (Criteria) this;
        }

        public Criteria andErrorFromNotIn(List<String> values) {
            addCriterion("error_from not in", values, "errorFrom");
            return (Criteria) this;
        }

        public Criteria andErrorFromBetween(String value1, String value2) {
            addCriterion("error_from between", value1, value2, "errorFrom");
            return (Criteria) this;
        }

        public Criteria andErrorFromNotBetween(String value1, String value2) {
            addCriterion("error_from not between", value1, value2, "errorFrom");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_operation_log
     *
     * @mbggenerated do_not_delete_during_merge Fri Mar 30 16:48:55 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_operation_log
     *
     * @mbggenerated Fri Mar 30 16:48:55 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}